#!/usr/bin/env zsh
# Deploy local code to the Raspberry Pi

local sourcePath="$(git-directory-root)/remote/"
local destinationPath="loial:./local/loial"

rsync \
  -avz \
  --exclude='__pycache__/' \
  --delete \
  --progress \
  "$sourcePath" \
  "$destinationPath"
