#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import sys

from pathlib import Path
libDirectory = str(Path(__file__).parent / 'lib')
sys.path.append(libDirectory)
from waveshare_epd import epd7in5_V2
from PIL import Image,ImageDraw,ImageFont

picturePath = sys.argv[1]

try:
    epd = epd7in5_V2.EPD()
    epd.init()
    epd.Clear()
    Himage = Image.open(picturePath)
    epd.display(epd.getbuffer(Himage))

except IOError as e:
    print(e)

sys.exit(0)

# # Get paths
# pictureDirectory = str(here.parent / 'pictures')
#
# # Find the a random file in pictureDirectory
# allPictures = list(Path(pictureDirectory).glob('*.jpg')) + \
#     list(Path(pictureDirectory).glob('*.png'))
# # print(pictureDirectory)
# # print(allPictures)
# randomPicture = str(allPictures[0])
# print(randomPicture)

# Imports
