#!/usr/bin/env zsh
# Deploy local code to the Raspberry Pi

local sourcePath="$(git-directory-root)/"
local destinationPath="loial:./local/loial"

rsync \
  -avz \
  --include='/display' \
  --include='/main' \
  --include='/pictures/***' \
  --exclude='.git' \
  --exclude='__pycache__/' \
  --include='/lib/***' \
  --exclude='*' \
  --delete \
  --progress \
  "$sourcePath" \
  "$destinationPath"
